### ISSUE TITLE
to you think these lines are correct (the backward function)?

### ISSUE THREAD

**Issue by ashual** [ashual/dl-ex1#1]
https://github.com/ashual/dl-ex1/blob/b2686e448b79163ccd1e10230a7cafbd76ce559c/question2/requ.py#L9

**Comment by itamartalmon** [comment]
Yes, it looks just fine.

**Comment by itamartalmon** [comment]
Sorry, im stupid. this lines are not correct. we are acting as if the derivative is 2 and not 2*input.
It should be also have (I think):
grad_input.mul(input)
